import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import ClientOnlyNavBar from "@/_components/NavBarConditional";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import GlobalError from "./global-error";
import { Suspense } from "react";
import Loading from "./condidats/loading";
// import { getServerSession } from "next-auth";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Macobate app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();
  return (
    <html lang="en">
      <ClerkProvider>
        <ErrorBoundary fallback={<GlobalError />}>
          <body className={inter.className}>
            <ClientOnlyNavBar />
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </body>
        </ErrorBoundary>
      </ClerkProvider>
    </html>
  );
}
