import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ClerkProvider, SignedOut, SignInButton } from "@clerk/nextjs";
import ClientOnlyNavBar from "@/_components/NavBarConditional";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Macobate ouvrier app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ClientOnlyNavBar />
          <SignedOut>
            <SignInButton />
          </SignedOut>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
