import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import ClientOnlyNavBar from "@/_components/NavBarConditional";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import GlobalError from "./global-error";
import { Suspense } from "react";
import Loading from "./condidats/loading";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Macobate app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();
  return (
    <html lang="en">
      <ErrorBoundary fallback={<GlobalError />}>
        <body className={inter.className}>
          <ClientOnlyNavBar />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Toaster position="top-right" />
        </body>
      </ErrorBoundary>
    </html>
  );
}
